FIRST_NEAREST_NEIGHBORS_CUTOFF = 3.5
SECOND_NEAREST_NEIGHBORS_CUTOFF = 4.5
THIRD_NEAREST_NEIGHBORS_CUTOFF = 5.3

# For FCC the first nearest neighbor is 12
NUM_FIRST_NEAREST_NEIGHBORS = 12
# For FCC the second nearest neighbor is 6
NUM_SECOND_NEAREST_NEIGHBORS = 6
# For FCC the third nearest neighbor is 6
NUM_THIRD_NEAREST_NEIGHBORS = 24
