FIRST_NEAREST_NEIGHBORS_CUTOFF = 3.5
SECOND_NEAREST_NEIGHBORS_CUTOFF = 4.5
THIRD_NEAREST_NEIGHBORS_CUTOFF = 5.3
FOURTH_NEAREST_NEIGHBORS_CUTOFF = 5.9
FIFTH_NEAREST_NEIGHBORS_CUTOFF = 6.5
SIXTH_NEAREST_NEIGHBORS_CUTOFF = 7.1
SEVENTH_NEAREST_NEIGHBORS_CUTOFF = 7.6

# For FCC the first nearest neighbor is 12
NUM_FIRST_NEAREST_NEIGHBORS = 12
# For FCC the second nearest neighbor is 6
NUM_SECOND_NEAREST_NEIGHBORS = 6
# For FCC the third nearest neighbor is 6
NUM_THIRD_NEAREST_NEIGHBORS = 24
# For FCC the fourth nearest neighbor is 12
NUM_FOURTH_NEAREST_NEIGHBORS = 12
# For FCC the fifth nearest neighbor is 24
NUM_FIFTH_NEAREST_NEIGHBORS = 24
# For FCC the sixth nearest neighbor is 12
NUM_SIXTH_NEAREST_NEIGHBORS = 8
# For FCC the seventh nearest neighbor is 48
NUM_SEVENTH_NEAREST_NEIGHBORS = 48
